# Based off of https://github.com/lowlighter/metrics
name: Metrics
on:
  # Daily updates
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: agailloty
          template: classic
          base: header, activity, community, repositories, metadata
          config_animations: yes
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, jupyter notebook, less, makefile, qmake, lex, cmake, shell, javascript
          plugin_languages_skipped: jupyter notebook
          commits_authoring: firstname lastname, username, mr.clerisaxel@hotmail.fr
          plugin_isocalendar: yes
